version: '3'

services:
  app:
    build: .
    restart: always
    command: sh -c "flake8 --ignore=E501 . && 
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: stroemer_db
      POSTGRES_USER: faridmagh
      POSTGRES_PASSWORD: ADADfgflslksflkoeWEW34dfdTZT56
    user: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/datav12
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A stroemer_test_farid worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - app
      - rabbitmq

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A stroemer_test_farid beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - app
      - rabbitmq

volumes:
  postgres_data:
