version: '3'

services:
  app:
    build: .
    restart: always
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: stroemer_db
      POSTGRES_USER: faridmagh
      POSTGRES_PASSWORD: ADADfgflslksflkoeWEW34dfdTZT56
    volumes:
      - postgres_data:/var/lib/postgresql/datav12


volumes:
  postgres_data:
