openapi: 3.0.0
info:
  title: Blog API
  version: 1.0.0
  description: A simple RESTful API for managing blog posts and comments

paths:
  /posts:
    get:
      summary: Retrieve all posts
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      summary: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          description: The created post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Bad request (e.g., invalid payload)
        '500':
          description: Internal server error

  /posts/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ID of the post to retrieve
        schema:
          type: integer
    get:
      summary: Retrieve a specific post
      responses:
        '200':
          description: The requested post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found
        '500':
          description: Internal server error
    put:
      summary: Update a post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: The updated post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found
        '400':
          description: Bad request (invalid payload)
        '500':
          description: Internal server error
    delete:
      summary: Delete a post
      responses:
        '204':
          description: Post deleted
        '404':
          description: Post not found
        '500':
          description: Internal server error

  /comments:
    get:
      summary: Retrieve all comments
      parameters:
        - name: post_id
          in: query
          required: false
          description: ID of the post to retrieve comments for
          schema:
            type: integer
      responses:
        '200':
          description: A list of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
    post:
      summary: Create a new comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '201':
          description: The created comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: Bad request (e.g., invalid payload)
        '500':
          description: Internal server error

  /comments/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ID of the comment to retrieve
        schema:
          type: integer
    get:
      summary: Retrieve a specific comment
      responses:
        '200':
          description: The requested comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '404':
          description: Comment not found
        '500':
          description: Internal server error
    put:
      summary: Update a comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '200':
          description: The updated comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '404':
          description: Comment not found
        '400':
          description: Bad request (invalid payload)
        '500':
          description: Internal server error
    delete:
      summary: Delete a comment
      responses:
        '204':
          description: Comment deleted
        '404':
          description: Comment not found
        '500':
          description: Internal server error

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        body:
          type: string
        user:
          $ref: '#/components/schemas/User'
      required:
        - id
        - title
        - body
        - user

    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
          format: email
        body:
          type: string
      required:
        - id
        - name
        - email
        - body

    User: # in case we implement user Model
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - name
        - email
